### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by atseniuk** [nlieb/ualberta-enroll#2]
Hey could you please supply more usage information on these scripts. I have experience with Python but my js is lacking and I am lost at trying to use this.

**Comment by nlieb** [comment]
What issue are you having?

**Comment by atseniuk** [comment]
I have download git, created credential file and tried to run yarn file but to no avail. Can you provide step by step instructions. As well will this just instantly enroll any class in watch list?

On Mar 14, 2018, at 2:50 PM, Nathan Liebrecht <notifications@github.com<mailto:notifications@github.com>> wrote:


What issue are you having?

**Comment by nlieb** [comment]
The readme has been updated, let me know if that works for you. If you have any further issues, please paste the full log with the error you encountered and steps to reproduce the error.

**Comment by nlieb** [comment]
If you have any issues, please open another issue with the above details
